### ISSUE TITLE
Question: How to work with react-native-multipeer?

### ISSUE THREAD

**Issue by qalqi** [kirillzyusko/react-native-wifi-p2p#11]
Can you please illustrate how do we communicate with iOS devices with `react-native-multipeer` and Android devices with `react-native-wifi-p2p`?

**Comment by kirillzyusko** [comment]
@qalqi Do I correct understand, that you want to connect Android device with iOS using p2p connection?

**Comment by qalqi** [comment]
Yep

**Comment by kirillzyusko** [comment]
I'm afraid you can't... Because mutipeer connectivity cannot connect iOS and Android devices. It's not a react-native restriction - it's a platform restriction (since they are used different approach in realisation) :(
You need to write your own implementation I think

**Comment by qalqi** [comment]
I was able to connect a Windows sdevice, a macbook device and a iOS device to WIFI direct group created by `createGroup` 
Only thing I need now, at least in iOS device to be able to send a message

**Comment by kirillzyusko** [comment]
Hm, have you tried to call `send` function from `react-native-multipeer`?
Or call `sendMessage` on Android side in order to send some data to iOS devices?

**Comment by qalqi** [comment]
iOS to iOS, peer advertising and connecting is working fine.
Create a WIFI Direct group from one Android device and able to connect to it with WIFI Direct group passphrase then create a Multipeer iOS to iOS connection.

Now, Android to iOS is something I haven't been able to figure out.

**Comment by kirillzyusko** [comment]
I think, I can't help you with this issue, unfortunately.
If you find a solution, please, write it here

**Comment by kirillzyusko** [comment]
@qalqi And also you can have a look on https://developers.google.com/nearby/

**Comment by kirillzyusko** [comment]
@qalqi I close this issue. If you find something interesting, please leave your comment here. Thank you in advance.
