### ISSUE TITLE
Group creation is not defined on real-time

### ISSUE THREAD

**Issue by DarkDracoon** [kirillzyusko/react-native-wifi-p2p#18]
Device A:
- Device: Android
- OS: API 29 (Q)

Device B:
- Device: Android
- OS: API 28 (P)

Using the master version of react-native-wifi-p2p or the project itself for demonstration of the library API, I'm not able to represent a group creation in real-time on the opposite device under these two devices, by getting the available devices, even though it is available on connection info. Is this a known issue for the newer Android devices or so? Without this, I can't either connect.

**To Reproduce**
1. Open the example app
2. Create Group
3. On the guest (client that will connect to the group owner), press Get Available Devices button, and you'll get "isGroupOwner": false.

**Comment by kirillzyusko** [comment]
Hi @DarkDracoon 
Are you able to get available peers/discover them?

**Comment by DarkDracoon** [comment]
Yes @kirillzyusko, although the "isGroupOwner" has a really large delay on showing as a group owner.

**Comment by kirillzyusko** [comment]
@DarkDracoon Did you request COARSE_LOCATION and FINE_LOCATION permissions?
Also you need turn on GPS/Location service: https://stackoverflow.com/questions/50475371/android-wifi-direct-p2p-not-able-to-find-peers-on-android-8/53149375#53149375

**Comment by DarkDracoon** [comment]
Yes @kirillzyusko , I did turn on Location and requested the specific permissions. I may debug that tomorrow.

**Comment by kirillzyusko** [comment]
@DarkDracoon I'm looking forward to your results😎

**Comment by kirillzyusko** [comment]
@DarkDracoon Hi, any updates?

**Comment by kirillzyusko** [comment]
Closed due to inactivity.
