### ISSUE TITLE
a proposal: use firebase  testlab

### ISSUE THREAD

**Issue by NoamDev** [kirillzyusko/react-native-wifi-p2p#19]
What do you think about inserting some CI to your development?
You can first test using mocks, but then you can test using real devices with firebase testing lab.
It won't help you to connect to actual devices probably, but you _can_ check things like initializing discover peers. This way, you'd be able to generally test on new devices and android versions you do not possess.
it would have prevented my issue for examaple:)

**Comment by kirillzyusko** [comment]
Hi @NoamDev 
It sounds like an awesome idea😎
Unfortunately, right now I don't have enough time for implementing this CI pipeline😒
But you can shoot a MR - it's highly appreciate ☺️

**Comment by NoamDev** [comment]
Pardon? MR?

**Comment by kirillzyusko** [comment]
Ah, sorry.
In different VCS systems it's called different. So, in GitLab it's MR (merge request), in GitHub it's called PR (pull request). When I wrote MR I meant PR :)

**Comment by kirillzyusko** [comment]
@NoamDev I hope I see PR soon from you😄
In any case, in a couple of months I’ll try to add support myself - now I can’t, because I’m very busy😞
Thank you for the suggestion😎

**Comment by NoamDev** [comment]
Just to note, it turns out firebase testing lab does not support wifi
direct, so such idea, would have to be implemented using another provider.

**Comment by kirillzyusko** [comment]
Do you know any free providers, which give an access to wi-fi?

**Comment by NoamDev** [comment]
A quick google search suggested [kobiton](https://kobiton.com/).
Free plan includes 120 min/month and 50 devices.
And yes, they support wifi.
Worth a try I believe, but I too, don't have time for this currently.

**Comment by kirillzyusko** [comment]
@NoamDev Got it. Thank you for research.
Maybe after 1-2months I can try to integrate it :)
In any case - thank you for your time and idea! 😎
