### ISSUE TITLE
subscribeOnPeersUpdates doesn't fire at all it  doesn't show me the connected devices 

### ISSUE THREAD

**Issue by hajermay** [kirillzyusko/react-native-wifi-p2p#23]

**Comment by kirillzyusko** [comment]
It might be useful: https://github.com/kirillzyusko/react-native-wifi-p2p/issues/4

**Comment by hajermay** [comment]
@kirillzyusko  i tried solutions mentioned on #4 baut my problem that the function doesn't fire any more if i write only a console.log

**Comment by kirillzyusko** [comment]
What devices do you use?

**Comment by hajermay** [comment]
huawei y7 android 8.1.0 et  galaxy A40 android 10

**Comment by kirillzyusko** [comment]
Did you follow these caveats?
https://github.com/kirillzyusko/react-native-wifi-p2p/blob/master/README.MD#caveats

**Comment by hajermay** [comment]
@kirillzyusko  thanks a lot it ok now with this caveats ;)

**Comment by kirillzyusko** [comment]
You are welcome :)
