### ISSUE TITLE
Peer to peer audio streaming [Question]

### ISSUE THREAD

**Issue by mrsasuu** [kirillzyusko/react-native-wifi-p2p#24]
Is it possible to stablish a connection 1/N and instead of sending a local file use an audio stream just as a2dp would do over Bluetooth?

Thank you so much!

**Comment by kirillzyusko** [comment]
Hi @mrsasuu 
Thank you for your question.
I think [here](https://stackoverflow.com/questions/24549884/wifi-direct-streaming-video-from-one-device-to-other) is a good answer :)

**Comment by kirillzyusko** [comment]
I think I provided all info.
I'm going to close this issue due to inactivity :)
