### ISSUE TITLE
Devices is not showing in android 9

### ISSUE THREAD

**Issue by Suman199201** [kirillzyusko/react-native-wifi-p2p#25]
The nearby devices list is showing in android 7 and the lower version phone, but not showing in android 9 . Can you please help me on that

**Comment by kirillzyusko** [comment]
Hi @Suman199201 
Did you follow https://github.com/kirillzyusko/react-native-wifi-p2p#caveats instructions?

**Comment by kirillzyusko** [comment]
Since there was no answer for a long time, I close this issue.
In the examples of version `3.0.0`, in componentDidMount I specifically put a request with permissions in order to avoid the appearance of this issue in the future.
