### ISSUE TITLE
App Crashing when clicking on Connect Button

### ISSUE THREAD

**Issue by sharmakumaraditya** [kirillzyusko/react-native-wifi-p2p#27]
Whenever i am clicking the Connect , Create Group or Send Button the App is Crashing and when i am pressing other buttons nothing is happening, can anyone please help me with this. The app is crashing again and again and to no success i was able to fix it.

**Comment by kirillzyusko** [comment]
Hi @sharmakumaraditya 
1. Does your device support p2p feature? Are you sure, that wifi enabled, when you call `createGroup`?
2. Did you call `init` method in the beginning?
3. Could you capture logs via `adb logcat` and send them here as `*.txt` file?

**Comment by sharmakumaraditya** [comment]
link to the txt file : [log.txt](https://github.com/kirillzyusko/react-native-wifi-p2p/files/4865876/log.txt)
1. Yes my Device does support p2p

Thanks for the quick reply

**Comment by kirillzyusko** [comment]
It looks like `state.devices` is empty. Then `state.devices[0].deviceAddress` will give you an error.
Am I correct?

**Comment by sharmakumaraditya** [comment]
I actually haven't checked that , i am just using this example https://github.com/kirillzyusko/react-native-wifi-p2p-example , i have just cloned this repo and actually i am trying to run this app.

**Comment by kirillzyusko** [comment]
Can you attach log when you do following:
1. Open app
2. Call `init`
3. Call `createGroup`

**Comment by sharmakumaraditya** [comment]
[log.txt](https://github.com/kirillzyusko/react-native-wifi-p2p/files/4866419/log.txt)

This is the log file for create group

**Comment by kirillzyusko** [comment]
@sharmakumaraditya cool. But I see only JS logs. I'd like to see all logs (including Java). Could you please capture it via `adb logcat` comand?

**Comment by sharmakumaraditya** [comment]
Sure i got it, the app crashes when the create group is clicked more than once.
