### ISSUE TITLE
Appearance files in receiver mobile gallery

### ISSUE THREAD

**Issue by sandipchandra17** [kirillzyusko/react-native-wifi-p2p#31]
To display received file likes image or video in gallery we can look for the below:
Link: https://stackoverflow.com/questions/2170214/image-saved-to-sdcard-doesnt-appear-in-androids-gallery-app

**Comment by kirillzyusko** [comment]
I got it
I think I will change the source of this library in the nearest days and publish it under `3.1.0` version (if I can not find another way for force-scanning gallery).

**Comment by kirillzyusko** [comment]
Changes are shipped in https://github.com/kirillzyusko/react-native-wifi-p2p/commit/a89d517247055e6e75beefac29ecdf4fa9541a10
I'm going to test it today evening. If everything is fine I will publish it today evening.

**Comment by sandipchandra17** [comment]
Great job.. thanks

**Comment by kirillzyusko** [comment]
@sandipchandra17 If you want - you can test it and give me your feedback. Merely install this package from github and rebuild your app. And you will be able to use new feature with `forceToScanGallery`.
Also in this case you can save my time and I can spend it on fixing other issues that you reported :)

**Comment by sandipchandra17** [comment]
I can't download the files. If you can provide me somehow or directly publish I will test and let you know.

**Comment by kirillzyusko** [comment]
@sandipchandra17 sure, I can.
Just change this line in package.json:
```
"react-native-wifi-p2p": "github:kirikzyusko1996/react-native-wifi-p2p#master"
```
And re-install your dependencies.

**Comment by sandipchandra17** [comment]
Installed successfully 3.1.0 but getting an error when i click on receive file. I am passing true as 3rd argument from app.js receive file method. 
![Screenshot_20200709-190826_PassOn](https://user-images.githubusercontent.com/42357868/87049212-4fae9080-c21a-11ea-88d0-251a2ac7b7ad.jpg)

I think this is due to one callback you added in manager module- receiveFile method but index.js sending 3 argument.

**Comment by kirillzyusko** [comment]
index.js sending 4:     

`WiFiP2PManager.receiveFile(folder, fileName, forceToScanGallery, (pathToFile) => {`

Can you send me code snippet how do you use new method?

**Comment by sandipchandra17** [comment]
Sending true from app.js - receiveFile method.
![Screenshot_20200709-190826_PassOn](https://user-images.githubusercontent.com/42357868/87064092-df5d3a80-c22c-11ea-8489-4004dd382612.jpg)

**Comment by sandipchandra17** [comment]
Passing true from receiveFile method in app.js file:

![20200709_213926](https://user-images.githubusercontent.com/42357868/87064357-3a8f2d00-c22d-11ea-8694-870da6bb0398.jpg)

**Comment by kirillzyusko** [comment]
Weird.
I will test it.

**Comment by sandipchandra17** [comment]
Ok.. also along with this you can check this in yiur test if the previous one not working.

I found another info for different androis version not sure helpful or not:::
public void refreshAndroidGallery(Uri fileUri) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            Intent mediaScanIntent = new Intent(
                    Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
            mediaScanIntent.setData(fileUri);
            mContext.sendBroadcast(mediaScanIntent);
        } else {
            mContext.sendBroadcast(new Intent(
                    Intent.ACTION_MEDIA_MOUNTED,
                    Uri.parse("file://" + Environment.getExternalStorageDirectory())));
        }
    }



Link: https://stackoverflow.com/questions/4144840/how-can-i-refresh-the-gallery-after-i-inserted-an-image-in-android

**Comment by kirillzyusko** [comment]
Will be shipped in 3.1.0

**Comment by sandipchandra17** [comment]
I tested this in android 7 and android 9 mobile working fine.. only one mobile lenovo k5note android 5 not refreshing gallery dont know why. May be mobile issue..

**Comment by kirillzyusko** [comment]
Or android specific version issue. I don't have a lot of android devices. Only Xiaomi and Huawei.
On both everything was working fine.
That's why I published new version.

**Comment by sandipchandra17** [comment]
Okay fine then even my 2 android phones working fine in sumsung and geonee.
