### ISSUE TITLE
Data flow clarifications

### ISSUE THREAD

**Issue by micahbule** [kirillzyusko/react-native-wifi-p2p#39]
Based on the documentation, I need to clarify some workflow concerns.

- It seems like data flow, that is sending messages or files, is only available in the form of the client sending data to the server. Can the server use the same methods and send messages/files back to the client?
- If no, then what would be the ideal design for 2-way communication between devices? As I understand that a device can be both a client and a server but not simultaneously.

I tried to search for specific protocols regarding WiFi Direct but I can't seem to find anything that states how data is being transferred from one device to another.

Thanks.

**Comment by 92sajid110** [comment]
hello @kirillzyusko ,
thanks for this great library.
My question is that can i send big files (.mp4,.pdf,or any file)like shareit using this library or only images or messages.

**Comment by kirillzyusko** [comment]
Hi @92sajid110 
The size of file doesn't matter. I was able to successfully transfer files ~10Mb (but it's still relatively small size). I didn't try to send really large files (several gigabytes). But I don't think there will be any restrictions. Let me know if you find them 😉

**Comment by kirillzyusko** [comment]
Closed since https://github.com/kirillzyusko/react-native-wifi-p2p/pull/61 was merged
