### ISSUE TITLE
DeviceEventEmitter.removeListener is deprecated

### ISSUE THREAD

**Issue by Kacper1104** [kirillzyusko/react-native-wifi-p2p#49]
Hi, you're using a deprecated way of removing event listener. Currently the supported way of unsubscribing the events is to perform remove() function on subscribtion which is returned by addListener() function. Are you planning to improve this part?  
![image](https://user-images.githubusercontent.com/37913081/136009378-e7dbaf5b-493e-4a58-977b-3b2afa1400c3.png)

index.js line 27

**Comment by kirillzyusko** [comment]
Hi @Kacper1104 Yes, I was planning :)

I think it's because of RN 0.65?

How did you plug in TypeScript to this project? I think this package doesn't have `.d.ts` file.

Could you please provide small code example, when you see this warning?
