### ISSUE TITLE
transmit an image from a camera

### ISSUE THREAD

**Issue by Luanfv** [kirillzyusko/react-native-wifi-p2p#50]
I'm starting a project in which I need to get the images from a camera via wifi, is it possible to do this through this lib, if so, how?

Thank you for your attention, hug.

**Comment by kirillzyusko** [comment]
Hi @Luanfv 

I think yes, you can transfer any file. If you just need to take a picture (`react-native-camera` will return a path to file, which you can pass in `sendFile` afterwards) and send it to another device, then this is possible. But if you need to send streaming data, then I think that this can be problematic and, most likely, the code of that library will need to be changed.

I hope I answered on your question 🙂
