### ISSUE TITLE
Could not resolve all files for configuration ':react-native-wifi-p2p:classpath'

### ISSUE THREAD

**Issue by aminisaeed** [kirillzyusko/react-native-wifi-p2p#58]
hi
it install without problem 
but when i want to run on simulator this error apear:
Could not resolve all files for configuration ':react-native-wifi-p2p:classpath'. > Could not find builder-3.3.0.jar (com.android.tools.build:builder:3.3.0).
Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.0/builder-3.3.0.jar

when i check the "Could not find builder-3.3.0.jar" address it was 404 not found
how should i solve this problem?
I need this library

**Comment by kirillzyusko** [comment]
Hi @aminisaeed 
I clicked a little nk and download has begun. Maybe something is wrong with your network configuration and it can not download because the resource is blocked?
Or maybe the page was under temporary maintenance?
What happens if you follow the link?

**Comment by aminisaeed** [comment]
![image](https://user-images.githubusercontent.com/53213776/201489193-4c6d232e-6cb0-4eb3-a22c-bcc545e5e4d0.png)


 result for me

**Comment by kirillzyusko** [comment]
@aminisaeed weird, but when I click on it - download begins 🤷‍♂️ 

<img width="242" alt="image" src="https://user-images.githubusercontent.com/22820318/201527818-ec0e5515-c49d-44a2-841c-f0bd9fc09509.png">

**Comment by aminisaeed** [comment]
The problem was from my VPN
I can download it with chrome but the speed was very slow

Now I have that file (30Mb) and again in the react native run android that error appears, and can't download this file

where should I put that file(builder.3.3.0.jar    30Mb) ? That in the installation react detect it and use it instead of download it?
In which folder???

**Comment by kirillzyusko** [comment]
@aminisaeed could you try this? https://stackoverflow.com/a/10834567/9272042

**Comment by aminisaeed** [comment]
The problem solved
The error was from my VPN and connection

**Comment by kirillzyusko** [comment]
Awesome! I'm closing the issue.
