### ISSUE TITLE
connectionInfo is not updated when connection closes

### ISSUE THREAD

**Issue by viniciuscb** [kirillzyusko/react-native-wifi-p2p#74]
the subscribe method is not catching the disconnect event, when I manually disconnect.

My disconnect code:

```javascript
  const disconnectFromAllDevices = () => {
    return new Promise((resolve, reject) => {
      getGroupInfo()
        .then(() => removeGroup())
        .then(() => {
          console.log('Succesfully disconnected!');
          resolve(null);
        })
        .catch(err => {
          console.error('Something gone wrong. Details: ', err);
          reject(err);
        });
    });
  };

```

**Comment by kirillzyusko** [comment]
@viniciuscb sorry, do I understand correctly, that it should be handled in user-written code and can't be handled on library level?

**Comment by viniciuscb** [comment]
Hi @kirillzyusko . I'll check that to be sure.

**Comment by viniciuscb** [comment]
there is a proposal to fix this issue in this PR: https://github.com/kirillzyusko/react-native-wifi-p2p/pull/78
