### ISSUE TITLE
TypeError: null is not an object (evaluating 'WiFiP2PManager.init')

### ISSUE THREAD

**Issue by JakobHartman** [kirillzyusko/react-native-wifi-p2p#94]
Getting this error on init. 

react-native: 0.72.6
IOS: 16.4
iPhone SE (Gen 3) Simulator
Typescript: 4.8.4

**Comment by kirillzyusko** [comment]
Hello @JakobHartman 

This library is not supporting iOS. You can wrap you `.init` method in `if (Platform.OS === 'android') {` to avoid this exception.
